os: linux
dist: xenial
language: node_js

node_js:
  - 8
  - 10
  - 12

jobs:
  include:
    - stage: test
    - stage: "Deploy to gh-pages"
      node_js: 12
      script: npm run build
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: build
        project_name: letscontribute-web
        repo: codinggirl/letscontribute
        target_branch: gh-pages
        deployment_file: true
        on:
          branch: master
