sudo: false
language: node_js

node_js:
  - 8
  - 10
  - 12

jobs:
  include:
    - stage: test
    - stage: deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  repo: codinggirl/letscontribute-web
  target_branch: gh-pages
  on:
    branch: master
